language: node_js

node_js:
  - 8

before_deploy: npm run build:docs

deploy:
  provider: pages
  local-dir: generated-docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  on:
    branch: master
