language: node_js

node_js:
  - 8

after_script:
  - sleep 10
  - cat ./coverage/lcov.info | npx coveralls

before_deploy:
  - npm run build:docs

deploy:
  provider: pages
  local-dir: generated-docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  on:
    branch: master
