version: 0.1
phases:
  install:
    commands:
    - npm install
    - npm install -g serverless
  build:
    commands:
    - serverless deploy --stage cicd | tee deploy.out
  post_build:
    commands:
      - . ./test.sh
